name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 2.7
        
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --path vendor/bundle
        
    - name: Run specs
      run: bundle exec rspec
        
    - name: Deploy application
      run: ./deploy_script.sh
